name: Generate Snake Game

on:
  schedule:
    # Executa diariamente
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: AntonioDev23
          outputs: dist/snake.svg

      - name: Push Snake SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Snake animation"
          file_pattern: dist/snake.svg
